# Generated by Django 4.1.1 on 2022-10-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('price', models.PositiveIntegerField(default=1000)),
                ('band', models.CharField(choices=[('5g', '5g'), ('4g', '4g'), ('3g', '3g')], default='4g', max_length=200)),
                ('display', models.CharField(choices=[('led', 'led'), ('amoled', 'amoled')], default='led', max_length=200)),
            ],
        ),
    ]
